import os
import requests
import time

from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


# ============================================================
# HEADSPIN CONFIGURATION
# ============================================================

HS_API_SERVER = os.getenv(
    "HEADSPIN_API_URL",
    "https://api-dev.headspin.io"
)

# API token is passed securely from Jenkins
TOKEN = os.getenv("HEADSPIN_API_TOKEN")

# APP ID is dynamically generated by Jenkins after APK upload
APP_ID = os.getenv("HEADSPIN_APP_ID")

# HeadSpin device ID
DEVICE_ID = os.getenv(
    "HEADSPIN_DEVICE_ID",
    "17081HFDD2699Y"
)

# HeadSpin WebDriver URL
HEADSPIN_WEBDRIVER_URL = os.getenv(
    "HEADSPIN_WEBDRIVER_URL",
    "https://dev-us-sny-9.headspin.io:7028/v0/e70f41cd904c4a3998fde1d73a13c947/wd/hub"
)


# ============================================================
# APPLICATION CONFIGURATION
# ============================================================

APP_PACKAGE = os.getenv(
    "APP_PACKAGE",
    "com.example.firecatalog"
)

APP_ACTIVITY = os.getenv(
    "APP_ACTIVITY",
    "com.example.firecatalog.MainActivity"
)


# ============================================================
# VALIDATE CONFIGURATION
# ============================================================

def validate_configuration():

    print()
    print("========================================")
    print("VALIDATING HEADSPIN CONFIGURATION")
    print("========================================")

    if not TOKEN:
        raise RuntimeError(
            "HEADSPIN_API_TOKEN environment variable is not set."
        )

    if not APP_ID:
        raise RuntimeError(
            "HEADSPIN_APP_ID environment variable is not set."
        )

    if not DEVICE_ID:
        raise RuntimeError(
            "HEADSPIN_DEVICE_ID environment variable is not set."
        )

    print(f"API Server: {HS_API_SERVER}")
    print(f"APP ID: {APP_ID}")
    print(f"Device ID: {DEVICE_ID}")
    print(f"App Package: {APP_PACKAGE}")
    print(f"App Activity: {APP_ACTIVITY}")
    print(f"WebDriver URL: {HEADSPIN_WEBDRIVER_URL}")

    print()
    print("Configuration validation successful.")


# ============================================================
# LOCK DEVICE
# ============================================================

def lock_device(
    token: str,
    device_id: str,
    *,
    automation: bool = False,
    api_server: str = HS_API_SERVER
) -> requests.Response:

    api_url = f"{api_server}/v0/devices/lock"

    headers = {
        "Authorization": f"Bearer {token}"
    }

    data = {
        "device_id": device_id
    }

    params = {}

    if automation:
        params["automation"] = True

    response = requests.post(
        api_url,
        headers=headers,
        json=data,
        params=params
    )

    return response


# ============================================================
# INSTALL APPLICATION
# ============================================================

def install_app(
    token: str,
    app_id: str,
    device_id: str,
    *,
    api_server: str = HS_API_SERVER
) -> requests.Response:

    api_url = (
        f"{api_server}/v1/app/"
        f"{app_id}/install/"
        f"{device_id}"
    )

    headers = {
        "Authorization": f"Bearer {token}"
    }

    print()
    print("----------------------------------------")
    print("INSTALLING APPLICATION")
    print("----------------------------------------")

    print(f"APP ID: {app_id}")
    print(f"Device ID: {device_id}")
    print(f"Install URL: {api_url}")

    response = requests.post(
        api_url,
        headers=headers
    )

    print()
    print(
        f"Install response status: "
        f"{response.status_code}"
    )

    print("Install response:")
    print(response.text)

    # Save response for Jenkins
    try:

        with open(
            "headspin_install_response.json",
            "w"
        ) as f:

            f.write(response.text)

        print()
        print(
            "Install response saved to "
            "headspin_install_response.json"
        )

    except Exception as e:

        print(
            f"Warning: Could not save install response: {e}"
        )

    return response


# ============================================================
# START CAPTURE SESSION
# ============================================================

def start_capture_session(
    token: str,
    device_id: str,
    *,
    api_server: str = HS_API_SERVER,
    **kwargs
) -> requests.Response:

    api_url = f"{api_server}/v0/sessions"

    headers = {
        "Authorization": f"Bearer {token}"
    }

    data = {
        "session_type": "capture",
        "allow_replace": True,
        "device_id": device_id
    }

    # Prevent network capture parameters
    kwargs.pop("network_capture", None)
    kwargs.pop("capture_network", None)

    data.update(kwargs)

    response = requests.post(
        api_url,
        headers=headers,
        json=data
    )

    return response


# ============================================================
# STOP CAPTURE SESSION
# ============================================================

def stop_capture_session(
    token: str,
    session_id: str,
    *,
    api_server: str = HS_API_SERVER
) -> requests.Response:

    api_url = f"{api_server}/v0/sessions/{session_id}"

    headers = {
        "Authorization": f"Bearer {token}"
    }

    data = {
        "active": False
    }

    response = requests.patch(
        api_url,
        headers=headers,
        json=data
    )

    return response


# ============================================================
# UNLOCK DEVICE
# ============================================================

def unlock_device(
    token: str,
    device_id: str,
    *,
    api_server: str = HS_API_SERVER
) -> requests.Response:

    api_url = f"{api_server}/v0/devices/unlock"

    headers = {
        "Authorization": f"Bearer {token}"
    }

    data = {
        "device_id": device_id
    }

    response = requests.post(
        api_url,
        headers=headers,
        json=data
    )

    return response


# ============================================================
# APPIUM AUTOMATION
# ============================================================

def run_appium_test():

    driver = None

    try:

        # ====================================================
        # APPIUM CAPABILITIES
        # ====================================================

        print()
        print("----------------------------------------")
        print("CONFIGURING APPIUM")
        print("----------------------------------------")

        options = UiAutomator2Options()

        options.platform_name = "Android"

        options.automation_name = "UiAutomator2"

        options.device_name = "Chromecast"

        options.udid = DEVICE_ID

        options.app_package = APP_PACKAGE

        options.app_activity = APP_ACTIVITY

        options.no_reset = True

        # Do not automatically launch application
        options.auto_launch = False

        # Terminate application when Appium session ends
        options.set_capability(
            "appium:shouldTerminateApp",
            True
        )

        options.new_command_timeout = 300

        # ====================================================
        # CONNECT TO HEADSPIN WEBDRIVER
        # ====================================================

        print()
        print("----------------------------------------")
        print("CONNECTING TO HEADSPIN WEBDRIVER")
        print("----------------------------------------")

        driver = webdriver.Remote(
            command_executor=HEADSPIN_WEBDRIVER_URL,
            options=options
        )

        print()
        print("Connected to HeadSpin device.")
        print("Appium session started.")

        # ====================================================
        # WAIT BEFORE AUTOMATION
        # ====================================================

        print()
        print("Waiting 10 seconds...")

        time.sleep(10)

        # ====================================================
        # VERIFY TITLE
        # ====================================================

        print()
        print("----------------------------------------")
        print("VERIFYING APPLICATION TITLE")
        print("----------------------------------------")

        wait = WebDriverWait(
            driver,
            20
        )

        title_xpath = (
            '//android.widget.TextView'
            '[@resource-id="com.example.firecatalog:id/title_text"]'
        )

        title_element = wait.until(
            EC.visibility_of_element_located(
                (
                    AppiumBy.XPATH,
                    title_xpath
                )
            )
        )

        title = title_element.text

        print()
        print(f"Title: {title}")
        print("PASS: Title is displayed.")

        # ====================================================
        # CLICK KITCHEN
        # ====================================================

        print()
        print("----------------------------------------")
        print("CLICKING KITCHEN")
        print("----------------------------------------")

        kitchen_xpath = (
            '//android.widget.TextView'
            '[@resource-id="com.example.firecatalog:id/row_header" '
            'and @text="Kitchen"]'
        )

        kitchen = wait.until(
            EC.element_to_be_clickable(
                (
                    AppiumBy.XPATH,
                    kitchen_xpath
                )
            )
        )

        kitchen.click()

        print(
            "Kitchen clicked successfully."
        )

        # ====================================================
        # CLICK HOME
        # ====================================================

        print()
        print("----------------------------------------")
        print("CLICKING HOME")
        print("----------------------------------------")

        home_xpath = (
            '//android.widget.TextView'
            '[@resource-id="com.example.firecatalog:id/row_header" '
            'and @text="Home"]'
        )

        home = wait.until(
            EC.element_to_be_clickable(
                (
                    AppiumBy.XPATH,
                    home_xpath
                )
            )
        )

        home.click()

        print(
            "Home clicked successfully."
        )

        # ====================================================
        # TEST PASSED
        # ====================================================

        print()
        print("========================================")
        print("APPIUM TEST PASSED")
        print("========================================")

        return True

    except Exception as e:

        # ====================================================
        # TEST FAILED
        # ====================================================

        print()
        print("========================================")
        print("APPIUM TEST FAILED")
        print("========================================")

        print(
            f"Error: {e}"
        )

        # ====================================================
        # SAVE FAILURE SCREENSHOT
        # ====================================================

        if driver:

            try:

                driver.save_screenshot(
                    "firecatalog_failure.png"
                )

                print(
                    "Failure screenshot saved: "
                    "firecatalog_failure.png"
                )

            except Exception as screenshot_error:

                print(
                    "Could not save screenshot: "
                    f"{screenshot_error}"
                )

        return False

    finally:

        # ====================================================
        # CLOSE APPIUM SESSION
        # ====================================================

        if driver:

            try:

                driver.quit()

                print()
                print(
                    "Appium session closed."
                )

            except Exception as e:

                print(
                    "Error while closing "
                    f"Appium session: {e}"
                )


# ============================================================
# MAIN EXECUTION FLOW
# ============================================================

def main():

    # ========================================================
    # VALIDATE CONFIGURATION
    # ========================================================

    validate_configuration()

    session_id = None

    device_locked = False

    test_passed = False

    try:

        # ====================================================
        # STEP 1: LOCK DEVICE
        # ====================================================

        print()
        print("========================================")
        print("STEP 1: LOCK DEVICE")
        print("========================================")

        lock_response = lock_device(
            TOKEN,
            DEVICE_ID,
            automation=True
        )

        print(
            f"Lock response: "
            f"{lock_response.status_code}"
        )

        print(
            f"Lock response body: "
            f"{lock_response.text}"
        )

        lock_response.raise_for_status()

        device_locked = True

        print()
        print(
            "Device locked successfully."
        )

        # ====================================================
        # STEP 2: INSTALL APPLICATION
        # ====================================================

        print()
        print("========================================")
        print("STEP 2: INSTALL APPLICATION")
        print("========================================")

        print()
        print(
            "Installing application uploaded "
            "by the current Jenkins build..."
        )

        print(
            f"APP ID: {APP_ID}"
        )

        install_response = install_app(
            TOKEN,
            APP_ID,
            DEVICE_ID
        )

        install_response.raise_for_status()

        print()
        print(
            "Application installed successfully."
        )

        # ====================================================
        # STEP 3: START CAPTURE SESSION
        # ====================================================

        print()
        print("========================================")
        print("STEP 3: START CAPTURE SESSION")
        print("========================================")

        session_response = start_capture_session(
            TOKEN,
            DEVICE_ID
        )

        print(
            f"Capture response: "
            f"{session_response.status_code}"
        )

        print(
            f"Capture response body: "
            f"{session_response.text}"
        )

        session_response.raise_for_status()

        session_data = session_response.json()

        session_id = session_data["session_id"]

        print()
        print(
            "Capture session started successfully."
        )

        print(
            f"Session ID: {session_id}"
        )

        # ====================================================
        # STEP 4: RUN APPIUM AUTOMATION
        # ====================================================

        print()
        print("========================================")
        print("STEP 4: RUN APPIUM AUTOMATION")
        print("========================================")

        print()
        print(
            "Capture session is active."
        )

        print(
            "Starting Appium automation..."
        )

        test_passed = run_appium_test()

        if test_passed:

            print()
            print(
                "Appium automation completed "
                "successfully."
            )

        else:

            print()
            print(
                "Appium automation completed "
                "with failures."
            )

    except Exception as e:

        # ====================================================
        # AUTOMATION FLOW ERROR
        # ====================================================

        print()
        print("========================================")
        print("AUTOMATION FLOW FAILED")
        print("========================================")

        print(
            f"Error: {e}"
        )

    finally:

        # ====================================================
        # STEP 5: STOP CAPTURE SESSION
        # ====================================================

        if session_id:

            print()
            print("========================================")
            print("STEP 5: STOP CAPTURE SESSION")
            print("========================================")

            try:

                stop_response = stop_capture_session(
                    TOKEN,
                    session_id
                )

                print(
                    f"Stop session response: "
                    f"{stop_response.status_code}"
                )

                print(
                    f"Stop session response body: "
                    f"{stop_response.text}"
                )

                stop_response.raise_for_status()

                print()
                print(
                    "Capture session stopped successfully."
                )

            except Exception as e:

                print(
                    "Failed to stop capture session: "
                    f"{e}"
                )

        else:

            print()
            print(
                "No capture session ID available."
            )

            print(
                "Skipping capture session stop."
            )

        # ====================================================
        # STEP 6: UNLOCK DEVICE
        # ====================================================

        if device_locked:

            print()
            print("========================================")
            print("STEP 6: UNLOCK DEVICE")
            print("========================================")

            try:

                unlock_response = unlock_device(
                    TOKEN,
                    DEVICE_ID
                )

                print(
                    f"Unlock response: "
                    f"{unlock_response.status_code}"
                )

                print(
                    f"Unlock response body: "
                    f"{unlock_response.text}"
                )

                unlock_response.raise_for_status()

                print()
                print(
                    "Device unlocked successfully."
                )

            except Exception as e:

                print(
                    "Failed to unlock device: "
                    f"{e}"
                )

        else:

            print()
            print(
                "Device was not locked."
            )

            print(
                "Skipping device unlock."
            )

        # ====================================================
        # FINAL RESULT
        # ====================================================

        print()
        print("========================================")
        print("HEADSPIN AUTOMATION FLOW COMPLETED")
        print("========================================")

        print(
            f"APP ID: {APP_ID}"
        )

        print(
            f"Device ID: {DEVICE_ID}"
        )

        if test_passed:

            print(
                "Final Result: PASS"
            )

        else:

            print(
                "Final Result: FAIL"
            )


# ============================================================
# SCRIPT ENTRY POINT
# ============================================================

if __name__ == "__main__":

    main()